---
development:
  dialect: postgres
  database: myblogs
  user: rasil
  password:
  host: 127.0.0.1
  pool: 5

test:
  url: '{{ envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/my-blogs_test?sslmode=disable" }}'

production:
  url: '{{ envOr "DATABASE_URL" "postgresql://postgres:YeeJduPYYyJbHhdQkMHLsMhLSfHgENms@junction.proxy.rlwy.net:14895/railway" }}'
